//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAY
    {
        public int IDTuyenDuong { get; set; }
        public int IDXe { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual TUYENDUONG TUYENDUONG { get; set; }
        public virtual XE XE { get; set; }
    }
}
