//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATVE_SOGHE
    {
        public int SoGhe { get; set; }
        public int IDDatVe { get; set; }
    
        public virtual DATVE DATVE { get; set; }
    }
}
