//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TUYENDUONG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TUYENDUONG()
        {
            this.CHAYs = new HashSet<CHAY>();
            this.CHUYENXEs = new HashSet<CHUYENXE>();
            this.NHANSUs = new HashSet<NHANSU>();
        }
    
        public int IDTuyenDuong { get; set; }
        public string DiemKhoiHanh { get; set; }
        public string DiemDen { get; set; }
        public Nullable<int> Status { get; set; }
    
        public virtual BEN BEN { get; set; }
        public virtual BEN BEN1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAY> CHAYs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHUYENXE> CHUYENXEs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHANSU> NHANSUs { get; set; }
    }
}
